@hostname = localhost
@port = 3333
@api_version = v1
@content_type = application/json

GET http://{{hostname}}:{{port}}/api/{{api_version}}/opening HTTP/1.1

###

GET http://{{hostname}}:{{port}}/api/{{api_version}}/openings HTTP/1.1

###

POST http://{{hostname}}:{{port}}/api/{{api_version}}/opening HTTP/1.1
Content-Type: {{content_type}}

{
  "role": "Sênior da vida e do universo",
  "company": "Ultrasoft",
  "location": "New York",
  "remote": true,
  "salary": 520000,
  "link": "vaga.com/vagadev"
}

###

DELETE http://{{hostname}}:{{port}}/api/{{api_version}}/opening HTTP/1.1

###

PUT http://{{hostname}}:{{port}}/api/{{api_version}}/opening HTTP/1.1
Content-Type: {{content_type}}

{}