@hostname = localhost
@port = 3333
@api_version = v1
@content_type = application/json

GET http://{{hostname}}:{{port}}/api/{{api_version}}/opening?id=2 HTTP/1.1

###

GET http://{{hostname}}:{{port}}/api/{{api_version}}/openings HTTP/1.1

###

POST http://{{hostname}}:{{port}}/api/{{api_version}}/opening HTTP/1.1
Content-Type: {{content_type}}

{
  "role": "Sênior Ruby Enginer",
  "company": "Ultrasoft",
  "location": "New York",
  "remote": true,
  "link": "https://vaga.com/vagadev/13308",
  "salary": 220000
}

###

DELETE http://{{hostname}}:{{port}}/api/{{api_version}}/opening?id=1 HTTP/1.1

###

PUT http://{{hostname}}:{{port}}/api/{{api_version}}/opening?id=2 HTTP/1.1
Content-Type: {{content_type}}

{
  "company": "Google"
}